export const texts = {
  app: {
    title: "Galeria de boda",
    description: "Aplicacion sencilla para compartir fotos de boda",
    nav: {
      home: "Inicio",
      gallery: "Galeria",
      upload: "Subir fotos",
      admin: "Admin",
    },
  },
  landing: {
    eyebrow: "Celebracion de boda",
    upload: "Subir fotos",
    viewGallery: "Ver galeria",
    latestMemories: "Ultimos recuerdos",
    viewFullGallery: "Ver galeria completa",
    latestEmpty: "Muy pronto apareceran aqui los ultimos recuerdos compartidos.",
  },
  common: {
    loading: "Cargando",
    success: "Exito",
    error: "Algo salio mal",
  },
  upload: {
    title: "Subir fotos",
    description: "Selecciona o toma fotos para compartir 📸",
    ready: "Tus fotos estan listas para subir.",
    selectionUpdated: "Tu seleccion se actualizo.",
    chooseAtLeastOne: "Selecciona al menos una imagen antes de subir.",
    validating: "Validando",
    optimizing: "Optimizando fotos...",
    validatingFiles: "Revisando tus archivos...",
    uploading: "Subiendo",
    uploadingKeepOpen: "Subiendo tus fotos. Mantén esta pagina abierta.",
    idle: "En espera",
    selectedPhotos: "Fotos seleccionadas",
    dropTitle: "Suelta tus imagenes aqui",
    dropSubtitle: "o toca para elegir desde tu dispositivo",
    dropHint: "Solo imagenes, hasta 10 MB cada una",
    dropAria: "Selecciona fotos para subir. Presiona Enter para elegir archivos.",
    inputAria: "Seleccionar fotos para subir",
    selectPhotos: "Seleccionar fotos",
    uploadButtonAria: "Subir fotos seleccionadas",
    uploadButton: "Subir fotos seleccionadas",
    validatingButton: "Validando...",
    uploadingButton: "Subiendo...",
    emptyTitle: "No hay fotos seleccionadas",
    emptyMessage: "Agrega imagenes para comenzar tu carga.",
    remove: "Quitar",
    removeAria: (fileName: string) => `Quitar ${fileName} de la seleccion`,
    notAddedTitle: "Algunos archivos no se agregaron:",
    successTitle: "Carga completada",
    successCount: (count: number) => `${count} foto${count === 1 ? "" : "s"} subida${count === 1 ? "" : "s"} con exito.`,
    failedTitle: "Algunas cargas fallaron",
    failedCount: (count: number) => `${count} carga${count === 1 ? "" : "s"} fallida${count === 1 ? "" : "s"}.`,
    progressUploading: (progress: number) => `${progress}% subiendo`,
    progressSuccess: "Subida con exito",
    progressFailedFallback: "La carga fallo",
    progressReady: "Lista para subir",
    flowAllSuccess: (count: number) =>
      `Carga completa. ${count} foto${count === 1 ? "" : "s"} subida${count === 1 ? "" : "s"} con exito.`,
    flowWithIssues: (successCount: number, errorCount: number) =>
      `Carga terminada con incidencias. ${successCount} exitosa${successCount === 1 ? "" : "s"} y ${errorCount} fallida${errorCount === 1 ? "" : "s"}.`,
  },
  gallery: {
    title: "Galeria",
    description: "Explora las fotos aprobadas compartidas por familiares y amigos.",
    emptyTitle: "Aun no hay fotos",
    emptyMessage: "La galeria aparecera aqui cuando los invitados suban fotos.",
    loadMore: "Cargar mas",
    loadingMore: "Cargando...",
    end: "Has llegado al final de la galeria.",
    loadMoreErrorTitle: "No se pudo cargar mas",
    loadMoreError: "No pudimos cargar mas fotos. Intentalo de nuevo.",
    loadingState: "Cargando mas fotos...",
    openAria: (fileKey: string) => `Abrir vista previa de la foto ${fileKey}`,
    photoAlt: (fileKey: string) => `Foto de boda ${fileKey}`,
    photoAltById: (id: string) => `Foto de boda ${id}`,
    modalTitle: "Vista previa de foto",
    modalCloseAria: "Cerrar vista previa de foto",
    modalClose: "Cerrar",
  },
  admin: {
    loginTitle: "Acceso admin",
    loginDescription: "Ingresa la contraseña admin para gestionar las fotos subidas.",
    password: "Contraseña",
    passwordAria: "Enviar contraseña admin",
    login: "Entrar al admin",
    verifying: "Verificando...",
    loginFailed: "No se pudo iniciar sesion. Intentalo de nuevo.",
    passwordRequired: "Ingresa la contraseña admin.",
    panelTitle: "Panel admin",
    panelDescription: "Gestiona las fotos subidas para este evento.",
    totalUploads: (count: number) => `Total de cargas: ${count}`,
    totals: (approved: number, hidden: number) => `Aprobadas: ${approved} | Ocultas: ${hidden}`,
    logout: "Cerrar sesion",
    loggingOut: "Cerrando sesion...",
    logoutAria: "Cerrar sesion de admin",
    noUploadsTitle: "Aun no hay cargas",
    noUploadsMessage: "Las fotos subidas apareceran aqui para moderacion.",
    actionFailedTitle: "La accion admin fallo",
    hide: "Ocultar",
    delete: "Eliminar",
    hideFailed: "No se pudo ocultar esta foto.",
    hideRetry: "No se pudo ocultar esta foto. Intentalo de nuevo.",
    hiddenSuccess: "Foto oculta.",
    deleteFailed: "No se pudo eliminar esta foto.",
    deleteRetry: "No se pudo eliminar esta foto. Intentalo de nuevo.",
    deletedSuccess: "Foto eliminada.",
    status: (approved: boolean) => `Estado: ${approved ? "aprobada" : "oculta"}`,
    uploadedAt: (value: string) => `Subida: ${value}`,
    fileKey: (value: string) => `Clave de archivo: ${value}`,
    unknownDate: "Fecha desconocida",
    previewAlt: (fileKey: string) => `Vista previa admin para ${fileKey}`,
    hideAria: (fileKey: string) => `Ocultar foto ${fileKey}`,
    deleteAria: (fileKey: string) => `Eliminar foto ${fileKey}`,
  },
  api: {
    upload: {
      invalidType: "Tipo de archivo no valido. Sube imagenes JPEG, PNG, WEBP, HEIC o HEIF.",
      fileTooLarge: "Archivo demasiado grande. El limite es de 10 MB.",
      missingFile: "Selecciona al menos una imagen antes de subir.",
      r2Failed: "No pudimos subir esta foto en este momento. Intentalo de nuevo.",
      supabaseFailed: "La imagen se subio, pero no se pudo guardar su registro. Intentalo de nuevo.",
      unexpectedResponse: "La carga fallo por una respuesta inesperada del servidor.",
      genericFailed: "La carga fallo. Intentalo de nuevo.",
      networkFailed: "Error de red al subir. Revisa tu conexion.",
      timeoutFailed: "La carga tardo demasiado. Intentalo de nuevo.",
    },
  },
} as const;
